version: '3.7'

# https://testdriven.io/blog/asynchronous-tasks-with-flask-and-redis-queue/
# http://snakeproject.ru/rubric/article.php?art=docker_flask_06.02.2019

services:
  bot:
    build:
      context: .
      dockerfile: dockerfile-python
    image: gss_exporter
    container_name: gss_exporter_bot
    ports:
      - 2980:80
    volumes:
      - ./bot/:/home/bot/
      - ./logs/:/home/logs/
    tty: true
    depends_on:
     - redis

  worker:
    image: gss_exporter
    container_name: gss_exporter_worker
    command: rq worker exporter --url redis://redis
    volumes:
     - ./bot/:/home/bot/
    depends_on:
     - redis

  redis:
    container_name: gss_exporter_redis
    image: redis:5-stretch
