version: '3.7'

# https://testdriven.io/blog/asynchronous-tasks-with-flask-and-redis-queue/
# http://snakeproject.ru/rubric/article.php?art=docker_flask_06.02.2019
# https://pythonise.com/feed/flask/building-a-flask-app-with-docker-compose

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: game-config-exporter
    container_name: game-config-exporter
    ports:
      - 2980:80
    volumes:
      - ./../bot/:/home/bot/
      - ./../logs/:/home/logs/
    tty: true
    depends_on:
     - redis

  worker:
    image: game-config-exporter
    container_name: game-config-worker
    command: rq worker exporter --url redis://redis
    volumes:
     - ./../bot/:/home/bot/
    depends_on:
     - redis

  redis:
    container_name: game-config-redis
    image: redis:5-stretch
